### ISSUE TITLE
TypeError: Cannot assign to read only property 'response' of object '[object Object]'

### ISSUE THREAD

**Issue by dwreski** [stevenvachon/broken-link-checker#202]
This happened after about twenty minutes of running on our site successfully. What more can I do to help troubleshoot this error?

├───OK─── https://github.com/omererdem/honeything
/usr/local/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:159
  err.response = response;
               ^
TypeError: Cannot assign to read only property 'response' of object '[object Object]'
    at addErrorData (/usr/local/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:159:16)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:567:25)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by bender2k14** [comment]
This looks like a duplicate of #184

**Comment by gauravgandhi1315** [comment]
@bender2k14 do you know how to add proxy to blc?

**Comment by bender2k14** [comment]
I do not. Sorry.

**Comment by gauravgandhi1315** [comment]
@dwreski Were you able to fix this issue?

**Comment by dwreski** [comment]
I believe it is, but I haven't been able to get back to this project. I will try over the coming week.
