### ISSUE TITLE
Object() has no method 'assign'

### ISSUE THREAD

**Issue by bonbons0220** [stevenvachon/broken-link-checker#30]
Did a global install of broken-link-checker
npm install -g broken-link-checker

Tried to run it and got this error:

```
/home/myhome/Projects/SciServer/Dev.das $blc http://www.sdss.org -ro

/home/myhome/.local/lib/node_modules/broken-link-checker/lib/internal/parseOptions.js:42
                options = Object.assign({}, defaultOptions, options);
                                 ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at parseOptions (/home/myhome/.local/lib/node_modules/broken-link-checker/lib/internal/parseOptions.js:42:20)
    at new SiteChecker (/home/myhome/.local/lib/node_modules/broken-link-checker/lib/public/SiteChecker.js:22:27)
    at run (/home/myhome/.local/lib/node_modules/broken-link-checker/lib/cli.js:467:14)
    at cli.input (/home/myhome/.local/lib/node_modules/broken-link-checker/lib/cli.js:144:3)
    at Object.<anonymous> (/home/myhome/.local/lib/node_modules/broken-link-checker/bin/blc:3:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
Then I looked at the readme: 

> Node.js >= 0.10 is required; < 4.0 will need Promise and Object.assign polyfills.

I have node 0.10.33. Not sure what module "< 4.0" refers to, but I also tried 
```npm install -g promise```
and 
```npm install -g object.assign```
but got the same error.
Did I not install the right object.assign module?

**Comment by stevenvachon** [comment]
> Node.js >= 0.10 is required; < 4.0 will need Promise and Object.assign polyfills.
From the readme.

**Comment by stevenvachon** [comment]
```js
require("es6-promise").polyfill();
require("object.assign").shim();
```
