### ISSUE TITLE
Why is the error in Linux？

### ISSUE THREAD

**Issue by icloudsme** [stevenvachon/broken-link-checker#38]
/broken-link-checker/lib/internal/parseOptions.js:42
		options = Object.assign({}, defaultOptions, options);
		                 ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at parseOptions (/home/avatar/node_modules/broken-link-checker/lib/internal/parseOptions.js:42:20)
    at new SiteChecker (/home/avatar/node_modules/broken-link-checker/lib/public/SiteChecker.js:22:27)
    at run (/home/avatar/node_modules/broken-link-checker/lib/cli.js:467:14)
    at cli.input (/home/avatar/node_modules/broken-link-checker/lib/cli.js:144:3)
    at Object.<anonymous> (/home/avatar/node_modules/broken-link-checker/bin/blc:3:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by stevenvachon** [comment]
> Node.js >= 0.10 is required; < 4.0 will need Promise and Object.assign polyfills.
