### ISSUE TITLE
Broken on Travis

### ISSUE THREAD

**Issue by sxlijin** [stevenvachon/broken-link-checker#66]
Running the blc binary breaks on my [Travis build](https://travis-ci.org/sxlijin/git-scm.com/jobs/211557519) (code [available here](https://github.com/sxlijin/git-scm.com/blob/09731840d0563551365a734a856cbf0144d30713/.travis.yml)) with the following error:

```
TypeError: Object function Object() { [native code] } has no method 'assign'
    at parseOptions (/home/travis/build/sxlijin/git-scm.com/node_modules/broken-link-checker/lib/internal/parseOptions.js:42:20)
    at new SiteChecker (/home/travis/build/sxlijin/git-scm.com/node_modules/broken-link-checker/lib/public/SiteChecker.js:22:27)
    at run (/home/travis/build/sxlijin/git-scm.com/node_modules/broken-link-checker/lib/cli.js:484:14)
    at cli.input (/home/travis/build/sxlijin/git-scm.com/node_modules/broken-link-checker/lib/cli.js:147:3)
    at Object.<anonymous> (/home/travis/build/sxlijin/git-scm.com/node_modules/broken-link-checker/bin/blc:3:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by stevenvachon** [comment]
Please read the readme:
> Node.js ... `< 4.0` will need `Promise` and `Object.assign` polyfills.

**Comment by sxlijin** [comment]
Thanks for the quick response, and sorry for failure to RTFM ):
